name: Docker Hub description
on:
  push:
    branches: ["main"]
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3.4.2
        env:
          DOCKERHUB_USERNAME: kbuley
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: kbuley/rustdevcontainer
  quayIODescription:
    name: Push README to Quay.io
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Quay.io Description
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_APIKEY: ${{ secrets.QUAY_API_KEY }}
        with:
          destination_container_repo: quay.io/kbuley/rustdevcontainer
          provider: quay
          readme_file: "README.md"
