name: Docker Hub description
on:
  push:
    branches: [main]
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml
jobs:
  dockerHubDescription:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0
      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v3.1.2
        env:
          DOCKERHUB_USERNAME: kbuley
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
          DOCKERHUB_REPOSITORY: kbuley/rustdevcontainer
