name: Misspells
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  misspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - uses: reviewdog/action-misspell@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          locale: "US"
          level: error
